steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: none
      list_align: after_alias
      pad_module_names: false
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

columns: 100
newline: native
cabal: true
