name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  stack-build:
    name: Stack - ghc-${{ matrix.ghc }} os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 9.2.2
          - 9.0.2
          - 8.10.7
        exclude:
          - os: macos-latest
            ghc: 9.0.2
          - os: macos-latest
            ghc: 8.10.7

    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml

    steps:
      - uses: actions/checkout@v3
        name: Checkout Source Code

      - uses: haskell/actions/setup@v2
        name: Setup Haskell Build Environment
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 2.7.5

      - uses: actions/cache@v3
        name: Cache dependencies
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles(env.STACK_YAML) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-stack-

      - name: Build
        run: |
          # Workaround for random errors on macos
          rm -rf ~/.stack/setup-exe-src ~/.stack/setup-exe-cache
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --system-ghc --ta '--quickcheck-tests 100000'

      - name: Haddock
        run: stack haddock --system-ghc

      - name : Prepare sdist
        run: stack sdist --system-ghc --ignore-check

      - name: Upload to Hackage
        if: matrix.ghc == '9.2.2' && matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/v')
        run: |
          export HACKAGE_KEY="${{ secrets.HACKAGE_TOKEN }}"
          stack upload --system-ghc --ignore-check webgear-core
          stack upload --system-ghc --ignore-check webgear-server
          stack upload --system-ghc --ignore-check webgear-openapi

  nix-build:
    name: Nix - ghc-${{ matrix.ghc }} os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ghc:
          - 924
          - 902
          - 8107
        exclude:
          - os: macos-latest
            ghc: 902
          - os: macos-latest
            ghc: 8107

    steps:
      - uses: actions/checkout@v3
        name: Checkout Source Code

      - uses: cachix/install-nix-action@v17
        name: Install Nix

      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: haskell-webgear
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Packages
        run: nix build -L --no-link .#webgear-core-ghc${{ matrix.ghc }} .#webgear-server-ghc${{ matrix.ghc }} .#webgear-openapi-ghc${{ matrix.ghc }}
