name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  nix-build:
    name: Nix - ghc-${{ matrix.ghc }} os-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - 9.10.1
          - 9.8.2
          - 9.6.6
          - 9.4.8
          - 9.2.8
          - 9.0.2

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: haskell-webgear
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Packages
        run: |
          GHC_VERSION=$(echo ${{ matrix.ghc }} | tr -d .)
          nix build --print-build-logs --no-link   \
            .#webgear-core-ghc${GHC_VERSION}       \
            .#webgear-server-ghc${GHC_VERSION}     \
            .#webgear-swagger-ghc${GHC_VERSION}    \
            .#webgear-swagger-ui-ghc${GHC_VERSION} \
            .#webgear-openapi-ghc${GHC_VERSION}    \
            .#webgear-benchmarks-ghc${GHC_VERSION}

      - name: Build Examples
        if: matrix.ghc == '9.10.1'
        run: |
          GHC_VERSION=$(echo ${{ matrix.ghc }} | tr -d .)
          nix build --print-build-logs --no-link           \
            .#webgear-example-users-ghc${GHC_VERSION}      \
            .#webgear-example-realworld-ghc${GHC_VERSION}

      - name: Benchmark
        run: |
          GHC_VERSION=$(echo ${{ matrix.ghc }} | tr -d .)
          BENCHMARK=$(nix build --no-link --json .#webgear-benchmarks-ghc${GHC_VERSION} | jq -r .[].outputs.out)
          ${BENCHMARK}/bin/users +RTS -N -RTS

  stack-build:
    name: Stack

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        name: Checkout Source Code

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Build Environment
        with:
          ghc-version: 9.8.2
          enable-stack: true

      - uses: actions/cache@v4
        name: Cache dependencies
        with:
          path: ~/.stack
          key: stack
          restore-keys: |
            stack-

      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --system-ghc --ta '--quickcheck-tests 100000'

      - name: Haddock
        run: |
          stack haddock --system-ghc \
            webgear-core             \
            webgear-server           \
            webgear-swagger          \
            webgear-swagger-ui       \
            webgear-openapi
